export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
